### PR TITLE
fix tiny typo that prevents from running cell

### PR DESCRIPTION
**Pull request by jsmentch**
change coverer to cover

### CODE REVIEW

**Comment by calebgeniesse** [comment]
thanks, @jsmentch!

do you know if this is backwards compatible with older versions of kmapper?
do you think we would be better off with just removing the “cover=“ keyword
entirely?

otherwise, makes sense to prioritize compatibility with the latest kmapper,
and I will merge this patch later today

**Comment by jsmentch** [comment]
I don't actually know, I think this was just a typo, not a compatibility issue. All of the other cells could run but the plots at the end didn't look right on my screen, maybe because of a newer version of networkx now? Formatting is off. (this is all new to me btw just getting back into python!)

Those more updated samples on the main landing page seem to work better for me (like the visualize_mapper_stages fn)

**Comment by calebgeniesse** [comment]
Ah, well nice catch then!

But quick question re: the plots that don't look right -- is there something else I should be looking at then? Or does this change fix things?

**Comment by calebgeniesse** [comment]
Just remembered that `kmapper` has tweaked the meaning/interpretation of its cover parameters a bit, and we should use a lower value for the "gain"/`perc_overlap` parameter to recover something closer to the original results.

e.g., after replacing the following line in the [`01_trefoil_knot.ipynb`](https://github.com/braindynamicslab/dyneusr-notebooks/blob/master/01_trefoil_knot/01_trefoil_knot.ipynb) 
```
cover = km.Cover(6, 0.8)
```
 
with 
```
cover = km.Cover(6, 0.5)
```

we get

image


@jsmentch, not sure if this is what you were referring too -- but this yields a much nicer looking plot that looks more similar to those shown on the main page of the dyneusr repository.

If you're up for making this additional change, we should include it here!

**Comment by jsmentch** [comment]
Yup that seems to have worked, thanks! I added a commit of that change

the plots at the end went from:
download2

to:
download3

**Comment by calebgeniesse** [comment]
Awesome, thanks! Merging now...

**Pull request merged**
